spring:
  datasource:
    url: jdbc:mysql://localhost:3306/atguigudb
    username: root
    password: 120074111
    driver-class-name: com.mysql.cj.jdbc.Driver
    #监控页
    druid:
      aop-patterns: com.atguigu.adimin.* #springbean监控
      filters: stat,wall #开启所有的功能
      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
        wall:
          enabled: true

      stat-view-servlet:   #监控页配置
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false

      web-stat-filter:  #web监控
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
  boot:
    admin:
      client:
        url: http://localhost:8888

mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

  jdbc:
    template:
      query-timeout: 3


#management是所有actuator的配置
#management.endpoint 对某个端点的具体配置
management:
  endpoints:
    enabled-by-default: true #暴露所有端点信息
    web:
      exposure:
        include: '*'  #以web方式暴露

  endpoint:
    health:
      show-details: always


























